### ISSUE TITLE
Unable to build, too many errors

### ISSUE THREAD

**Issue by Merith-TK** [dgrr/discordfs#1]
```
[developer@archlinux go-discordfs]$ go build
# discordfs
./bot.go:52:15: undefined: afero.Create
./bot.go:55:5: undefined: afero.Link
./bot.go:64:14: undefined: afero.Create
./bot.go:67:4: undefined: afero.Link
./bot.go:135:12: undefined: afero.OpenFile
./fuse.go:33:2: undefined: afero.Mkdir
./fuse.go:46:4: undefined: afero.MkdirAll
./fuse.go:47:4: undefined: afero.Link
./fuse.go:64:4: undefined: afero.Link
./fuse.go:115:2: undefined: afero.MkdirAll
./fuse.go:115:2: too many errors
```

**Comment by dgrr** [comment]
`go get -u -v github.com/dgrr/discordfs`

**Comment by Merith-TK** [comment]
Okay, it builds now, but understanding how to mount it is confusing, like where does it mount and do things?

**Comment by dgrr** [comment]
First, you need to configure it. `discordfs (your email)` once configured you'll be able to mount it. `discordfs (mountpoint)`

**Comment by Merith-TK** [comment]
yeah, i did that, but its forcing to mount to `/tmp/discordfs` but nothing is in that directory at all

**Comment by Merith-TK** [comment]
Also cant i feed it a bot token in the config file?

**Comment by dgrr** [comment]
> yeah, i did that, but its forcing to mount to `/tmp/discordfs` but nothing is in that directory at all
> 
> ```
> [developer@archlinux discordfs]$ discordfs /home/developer/discordfs/
> 2020/01/07 18:57:30 open /tmp/discordfs: is a directory
> ```

The `/tmp/discordfs` is a log file. It should not be a directory.

**Comment by dgrr** [comment]
> Also cant i feed it a bot token in the config file?

Yes, I think you can

**Comment by Merith-TK** [comment]
`2020/01/07 20:51:40 HTTP 401 Unauthorized, {"message": "401: Unauthorized", "code": 0}`
Well now that i know its a log file. 
it returns this

**Comment by Merith-TK** [comment]
okay that was wrong password

now im getting this
```
panic: HTTP 403 Forbidden, {"message": "Missing Access", "code": 50001}

goroutine 1 [running]:
main.downloadGuildMembers(0xc0000a6840, 0x12, 0xc000363de0, 0x17, 0xc0000cc3c0)
	/home/developer/Workspace/go-discordfs/main.go:203 +0x281
main.(*FS).fetch(0xc0000a8158, 0xc0000a8158, 0x0)
	/home/developer/Workspace/go-discordfs/fuse.go:61 +0x1d7
main.main()
	/home/developer/Workspace/go-discordfs/main.go:85 +0x7b8
```

**Comment by dgrr** [comment]
That seems to be some error related with the discord API
