### ISSUE TITLE
Since using, my account keeps wanting to buy nitro

### ISSUE THREAD

**Issue by Merith-TK** [dgrr/discordfs#2]
basically i keep getting the prompt to verify my accound, and recently it gave me a popup saying "if you want to buy nitro, you gotta verify your account"

This only started happening RIGHT AFTER i attempted to use this

**Comment by dgrr** [comment]
What? I really don't know what are you talking about. But yes, you'll need to verify your account to gain access though the API

**Comment by Merith-TK** [comment]
Hmm, its probably an extension i have in my browser

and alright,

**Comment by Merith-TK** [comment]
Hmm, its probably an extension i have in my browser

and alright,

**Comment by Merith-TK** [comment]
Can confirm, malicious extension got sideloaded, offending software and extension removed.
